### ISSUE TITLE
DuckDB Catalog Error

### ISSUE THREAD

**Issue by surajpaib** [ImagingDataCommons/idc-index#123]
**Describe the bug**
Download the latest `idc-index` and ran the below,

```bash
idc download-from-selection --series-instance-uid 1.3.6.1.4.1.14519.5.2.1.8421.4008.761093011533106086639756339870 --download-dir . 
```

This gave a 
```
duckdb.duckdb.CatalogException: Catalog Error: Table with name result_df does not exist!
Did you mean "pg_attrdef"?
```
Debug log: 
[error.log](https://github.com/user-attachments/files/16955810/error.log)

Python environment: 
Python 3.10.14 with
[pip-freeze.txt](https://github.com/user-attachments/files/16955825/pip-freeze.txt)

**To Reproduce**
Also tried this on a separate machine with a fresh environment (Python 3.10.10). Same error occurs. 

**Current workaround**
Not very familiar with duckdb but I thought it could be a variable scoping issue with duckdb as `result_df` is not available in the scope of the function `sql_query`

That did the trick! 

The modified function signature
```python
    def sql_query(self, sql_query, result_df): 
```

**Comment by fedorov** [comment]
@surajpaib sorry I missed this yesterday!

I ran into this independently while upgrading idc-index to v19. This should be resolved now by https://github.com/ImagingDataCommons/idc-index/pull/124, which added constraint on the duckdb version. The regression was due to duckdb 1.1.0.

The latest idc-index 0.7.0 should not have the issue, but please reopen if you still have problems!
