### ISSUE TITLE
Multi-threaded downloads

### ISSUE THREAD

**Issue by Dengjun21** [ImagingDataCommons/idc-index#135]
**Thank you all for your work!** 
But I have a doubt that when I want to download more efficiently by multithreading, only max worker=1 will start to download, as long as it is greater than 1, it will not execute the download, I don't know if this is a bug or the server doesn't support multithreading at the moment.  Here is my code:
```
def download_patient_data(patient_id):
    try:
        print(f"Downloading data for {patient_id}")
        c = index.IDCClient()
        c.download_from_selection(
            collection_id="nlst",
            patientId=patient_id,
            downloadDir=r"...",
        )
        print(f"Downloaded data for patient {patient_id}")
    except Exception as e:
        print(f"Failed to download data for patient {patient_id}: {e}")

with concurrent.futures.ThreadPoolExecutor(max_workers=1) as executor:
    futures = [executor.submit(download_patient_data, patient_id["PatientID"]) for patient_id in selected_patients]
    for future in tqdm(concurrent.futures.as_completed(futures), total=len(futures)):
        try:
            future.result()  
        except Exception as e:
            print(f"An error occurred: {e}")
```

**Comment by fedorov** [comment]
@Dengjun21 thanks for asking this question!

`idc-index` wraps `s5cmd`, which behind the scenes performs download very efficiently in parallel. When you call `download_from_selection()`, it will use the internal index to build the manifest of the files that correspond to the selection, and will pass that manifest to either `s5cmd run` or `s5cmd sync` commands, depending on the parameters you select. You can read about how `s5cmd` parallelizes download here: https://github.com/peak/s5cmd?tab=readme-ov-file#run-multiple-commands-in-parallel.

It is not recommended that you launch multiple download threads using `idc-index` in parallel, since each download operation is itself parallelized.

Does this answer your question?

**Comment by Dengjun21** [comment]
@fedorov Yeah,I think you've answered it comprehensively, thanks for answering my questions!
