### ISSUE TITLE
Download index csv and s5cmd binary at the time of the install

### ISSUE THREAD

**Issue by fedorov** [ImagingDataCommons/idc-index#3]
@vkt1414 can you look if it is possible to download those at the time package is installed?

**Comment by vkt1414** [comment]
> @vkt1414 can you look if it is possible to download those at the time package is installed?

I'm still figuring out a way but this article alarms the approach we are taking..

https://checkmarx.com/blog/automatic-execution-of-code-upon-package-download-on-python-package-manager/

Based on this, I don't know if downloading index and s5cme immediately after pip install is a good idea. Should we pursue this?

**Comment by fedorov** [comment]
@pieper what are your thoughts on this?

**Comment by pieper** [comment]
I think the assumption is that all the code and dependencies are installed during the pip install process, so that it importing and running the code is as efficient as possible.  I don't think it's desirable for the first run of the installed package to take longer than subsequent runs if that can be avoided.

I can also imagine that users would expect to be able to run an installed package without needing the network, while pip installing necessarily requires a network connection.

I would try to treat s5cmd like you would any other binary dependency of a python package.  You could look into how pydicom treats gdcm, for example.  Many python packages install command line tools that are then available in your shell (e.g. pip itself) so installing s5cmd in a similar way seems most consistent with current practice.

**Comment by fedorov** [comment]
I agree with Steve!

**Comment by vkt1414** [comment]
I don't know if I understand fully. I can certainly just include the CSV file and s5cmd binaries (for mac, linux and windows) with in the pip package.

**Comment by pieper** [comment]
> I can certainly just include the CSV file and s5cmd binaries (for mac, linux and windows) with in the pip package.

Yes, that's basically the idea, but I don't know if they want these big binary assets in the pypi package.  I just looked and the limit is 5GB, so actually it's probably okay.

Or maybe better to download them during the install process from another source - I haven't done it myself, but it would be good to look at how other packages handle this kind of thing.  It would be good to follow whatever we find to be the convention that other packages follow.  Especially the csv file, which will change often, might be better not to have in the package.

**Comment by fedorov** [comment]
> the csv file, which will change often, might be better not to have in the package.

Yes, that is exactly why I do not want to include it in the package.

**Comment by vkt1414** [comment]
Thanks, @pieper @fedorov  for your valuable input! I did figure out a way to download both the CSV index and platform-specific s5cmd binary at the pip installation step.
In the future, we decided to match the idc-index package version and IDC release version, so it will be straightforward to know which IDC release version is being used.

**Comment by fedorov** [comment]
Well done @vkt1414!

FYI, I added development status classifier: https://github.com/ImagingDataCommons/idc-index/commit/4b7d2b3b1ba0befe44be2e70994018b09189702b.
