### ISSUE TITLE
idc-index CSV is not packaged with the refactored organization of the repo

### ISSUE THREAD

**Issue by fedorov** [ImagingDataCommons/idc-index#41]
@jcfr it is my fault that I missed it during my testing, but we realized it only today that the CSV file that serves as the content of the index is not packaged in the wheel.

This is how we did it before: https://github.com/ImagingDataCommons/idc-index/blob/a39d961f28588e69683fcbb79a8c044bec1e5e8a/setup.py#L29.

Currently, since this file is not packaged, the fallback is activated and it is downloaded when the user instantiates the index: https://github.com/ImagingDataCommons/idc-index/blob/597aef6d20da12f3071eacdc11c844115a5743ba/idc_index/index.py#L35.

Before declaring this to be a bug and working on a solution, I would like to understand what is the recommendation/best practice on how this should be done? We discussed this initially, and thought that it is better to install this file at the time the package is installed, and to avoid surprising user by downloading it at runtime, but maybe that is not the best practice? Do you have a perspective on this?

**Comment by jcfr** [comment]
> re: that the CSV file that serves as the content of the index is not packaged in the wheel. 

Thanks for pointing this out. Packaging the csv file as part of the wheel would allow to streamline the implementation by avoiding runtime download (that would need to be updated by adding checksum verification as it currently only check[^1] for file existence)

As you said, it would avoid an additional download upon the first instantiation of the IDCClient.

To avoid uploading the cvs file (~45M) for each platform specific wheels, we could also create a wheel called `idc-s5cmd` that would be responsible to only install the `s5cmd`, that way we would be a good "citizen" and avoid re-uploading 90MB with each release of the `idx-index` wheel which would distributed as a pure-python one called `idx-index-X.Y.Z-py3-none-any.whl`.

Last, we could also look into having an other wheel responsible to only distribute the csv file, this wheel would be called `idc-index-csv`.

In the short term, I suggest to create `idc-s5cmd` as well as post an issue at https://github.com/peak/s5cmd suggesting the creation of `https://github.com/peak/s5cmd-python-distributions` so that a wheel called `s5cmd` is available for download.

[^1]: https://github.com/ImagingDataCommons/idc-index/blob/597aef6d20da12f3071eacdc11c844115a5743ba/idc_index/index.py#L34-L40

**Comment by jcfr** [comment]
Alternatively, we could also create https://github.com/ImagingDataCommons/s5cmd-python-distributions  (conceptually similar to https://github.com/scikit-build/cmake-python-distributions or https://github.com/scikit-build/ninja-python-distributions)

**Comment by jcfr** [comment]
@fedorov  I am happy to help by posting an issue at `https://github.com/peak/s5cmd-python-distributions`

**Comment by fedorov** [comment]
@jcfr we discussed this with @vkt1414 and agreed these are very cool suggestions! Yes, I think no one would be able to formulate the issue better for the `s5cmd` repo than you, it would be great if you could do it.

**Comment by jcfr** [comment]
> it would be great if you could do it.

:ok_hand: I will take care of this either this evening or tomorrow.

**Comment by jcfr** [comment]
Corresponding issue has been created:
* https://github.com/peak/s5cmd/issues/703
