### ISSUE TITLE
Missing Fields in IDC Index

### ISSUE THREAD

**Issue by varikmp** [ImagingDataCommons/idc-index#64]
Hello team,

I realized that some fields are missing in the IDC-INDEX such as:
- ImageType
- Patient Weight
- SliceThickness
- PixelSpacing
- tcia_species
- tcia_tumorLocation

Is there any other places that I can retrieve the data of those fields (I used BQ to access public IDC dataset).

Best regards,

**Comment by fedorov** [comment]
@varikmp `idc-index` contains a tiny subset of the metadata fields accompanying IDC public data. BigQuery has all of the fields. idc-index is populated from the BigQuery content, specifically driven by the queries in this folder of `idc-index-data` package https://github.com/ImagingDataCommons/idc-index-data/tree/main/scripts/sql.

We are very conservative with including fields in `idc-index`, since the goal is to minimize the size of the package, and support just the basic operations. We appreciate your feedback, and will consider how we can accommodate the additional fields you mentioned (in particular, species and tumorLocation fields are defined at the collection level, so we could come up with a way to include them without increasing the overall package size significantly).

You can access all of the attributes you mentioned through the BigQuery `dicom_all` table described in https://learn.canceridc.dev/data/organization-of-data/files-and-metadata#bigquery-tables-and-views.

Also note that `tcia_species` and `tcia_tumorLocation` fields will be deprecated and renamed to `collection_species` and `collection_tumorLocation`. The original naming was misleading, since IDC includes data from various sources, and not just from TCIA.

Please let me know if this addresses your question, or if you have any other feedback about idc-index.

**Comment by vkt1414** [comment]
Hi @varikmp, we have now made all metadata tables in Bigquery also available in AWS buckets public as parquet files. Please let me know if we can help you find the data, as this method does not require any GCP cloud credentials or billing account.
